apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: polling-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: polling-app-server
          servicePort: 80